services:
  worker:
    build: 
      context: .
      dockerfile: ./apps/worker/Dockerfile
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - code-compiler-network
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy


  api:
    build: 
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    networks:
      - code-compiler-network
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - code-compiler-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    networks:
      - code-compiler-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  code-compiler-network:
    driver: bridge
